/* Landing gate — 7 sections at 390 + 1440, marquee, tiers, klasemen, basket bar, no page errors. */
const { ok, launch, go, resetStores, text, minTapHeight, finish } = require('./_lib.cjs')

;(async () => {
  const { b, p, errs } = await launch({ width: 390, height: 844 })
  await resetStores(p)
  await go(p, '/')

  const ids = ['hook', 'hero', 'benefit', 'tier', 'cek-poin', 'golden-sale', 'klasemen']
  const order = await p.evaluate(ids => ids.map(id => { const el = document.getElementById(id); return el ? el.getBoundingClientRect().top + window.scrollY : -1 }), ids)
  ok(order.every(v => v >= 0), `7 sections present → ${JSON.stringify(order.map(Math.round))}`)
  ok(order.every((v, i) => i === 0 || v > order[i - 1]), 'sections in the specified order')

  const t = await text(p)
  ok(/Resique Turun Harga!/.test(t), 'hook title "Resique Turun Harga!" (exclamation)')
  ok(/Harga turun paling besar/.test(t) && !/Contoh harga turun/.test(t), 'hook drop card titled "Harga turun paling besar" (no "Contoh")')
  ok((await p.locator('#benefit ul > li').count()) === 5, '5 privilege blocks (diskon · ongkir · konsultasi · redeem · event)')
  ok(/Diskon belanja/.test(t) && /Gratis ongkir/.test(t) && /Gratis konsultasi bisnis/.test(t) && /Redeem poin/.test(t) && /Event tahunan eksklusif Resique/.test(t), 'all 5 privilege titles present')
  ok((await p.locator('#benefit ul > li svg').count()) >= 5, 'privilege blocks carry icons')
  ok(/Peringkat 1/.test(t) && (await p.locator('#klasemen ol li[data-rank="1"] svg').count()) === 1, 'klasemen leader card (rank 1 with trophy)')
  ok((await p.locator('#klasemen ol li[data-rank="2"] div[aria-hidden] > div').count()) === 1, 'klasemen rows carry spend bar')
  const ctaBg = await p.evaluate(() => getComputedStyle(document.getElementById('cek-poin')).backgroundColor)
  ok(ctaBg === 'rgb(33, 26, 90)', `CTA section is a navy block (${ctaBg})`)
  ok((await p.locator('#cek-poin ol li').count()) === 3, 'CTA section lists the 3 steps')
  ok(/Hingga 5%/.test(t) && !/0–5%/.test(t), 'diskon block reads "Hingga 5%" (no "0–5%")')
  const card = await text(p, '[data-rmc-card]')
  ok(/Resique Member Card/.test(card) && /Poin RMC/.test(card) && /Laundry 24 Jam Kuningan/.test(card) && /Winner/.test(card), 'CTA band shows the demo member RMC card (tier + poin)')
  // title marks: every section h2 + the hook h1 carry the highlighter on the last word; it draws in (scaleX 1) once in view
  for (const sel of ['#hook h1', '#benefit h2', '#tier h2', '#cek-poin h2', '#golden-sale h2', '#klasemen h2']) {
    await p.locator(sel).scrollIntoViewIfNeeded(); await p.waitForTimeout(900)
    const m = await p.evaluate(sel => { const el = document.querySelector(sel + ' .mark'); return el ? getComputedStyle(el, '::before').transform : 'missing' }, sel)
    ok(/^matrix\(0\.99|^matrix\(1/.test(m), `${sel} highlighter mark drawn in (${m.slice(0, 22)})`)
  }
  await p.evaluate(() => window.scrollTo(0, 0)); await p.waitForTimeout(300)
  ok(/Tingkatkan transaksi, dapatkan hadiahnya/.test(t), 'hero tagline')
  ok(/Cek poin-mu/.test(t), 'CTA "Cek poin-mu!"')
  ok((await p.locator('.marquee-track li').count()) >= 2, 'hero marquee has duplicated strip')
  ok((await p.locator('#tier h3:visible').count()) === 6, '6 tier cards visible (mobile ladder / desktop cards)')
  ok(/Mitra Apique Management/.test(t) && /minimal 3%/.test(t), 'Mitra floor 3% note')
  // RSQ-RMC-001 v2.0 §3: ongkir ≥ Rp500 rb (Starter–Intermediate) / ≥ Rp350 rb (Winner+); konsultasi 1/1/2 sesi per bulan; no "tanpa minimum"
  const tierTxt = await p.evaluate(() => [...document.querySelectorAll('#tier ol > li')].map(li => li.innerText.replace(/\s+/g, ' ')))
  ok(tierTxt.length === 6 && tierTxt.slice(0, 3).every(x => /min\. Rp500 rb/.test(x)) && tierTxt.slice(3).every(x => /min\. Rp350 rb/.test(x)), 'tier cards: ongkir 500 rb ×3 then 350 rb ×3 (policy §3)')
  ok(/1 sesi\/bln/.test(tierTxt[3]) && /1 sesi\/bln/.test(tierTxt[4]) && /2 sesi\/bln/.test(tierTxt[5]) && !/sesi\/bln/.test(tierTxt[0]), 'tier cards: konsultasi 1/1/2 sesi per bulan from Winner')
  ok(!/tanpa minimum|Tanpa min\./i.test(t) && !/mulai tier Champion/.test(t), 'no drifted claims (ultimate tanpa minimum / Gala Dinner by tier)')
  ok(/0 – ?8\.999\.999/.test(tierTxt[0]) && /9\.000\.000 – ?17\.999\.999/.test(tierTxt[1]) && /≥ 120\.000\.000/.test(tierTxt[5]), 'tier bands inclusive: 0–8.999.999, 9.000.000–17.999.999, ≥ 120.000.000')
  ok((await p.locator('#klasemen ol li').count()) === 10, 'klasemen shows 10 rows')

  // no horizontal scroll at 390
  const sw = await p.evaluate(() => ({ sw: document.documentElement.scrollWidth, cw: document.documentElement.clientWidth }))
  ok(sw.sw === sw.cw, `no horizontal scroll (scrollWidth ${sw.sw} = clientWidth ${sw.cw})`)

  // basket bar hidden when empty, shown after add
  ok((await p.locator('[data-basket-bar]').getAttribute('aria-hidden')) === 'true', 'basket bar hidden when cart empty')
  await p.locator('#golden-sale button[aria-label^="Tambah"]').first().click()
  await p.waitForTimeout(400)
  ok((await p.locator('[data-basket-bar]').getAttribute('aria-hidden')) === 'false', 'basket bar visible after add')
  ok(/1 item/.test(await text(p, '[data-basket-bar]')), 'basket bar shows 1 item')
  const tap = await minTapHeight(p, '#golden-sale button, [data-basket-bar] a, [data-basket-bar] button')
  ok(tap >= 44, `tap targets ≥ 44px (min ${tap})`)

  // desktop
  await p.setViewportSize({ width: 1440, height: 900 })
  await p.waitForTimeout(500)
  const heights = await p.evaluate(ids => ids.map(id => document.getElementById(id).getBoundingClientRect().height), ['hero', 'benefit', 'tier'])
  ok(new Set(heights.map(h => Math.round(h / 50))).size >= 2 && heights[0] >= 280, `desktop sections vary in height (no uniform deck) → ${heights.map(Math.round)}`)
  const heroCols = await p.evaluate(() => { const g = document.querySelector('#hero .grid'); return g ? getComputedStyle(g).gridTemplateColumns.split(' ').length : 0 })
  ok(heroCols >= 12, `hero two-column grid on desktop (${heroCols} tracks)`)

  // hover motion (desktop): tier card lifts, klasemen row slides, nav link underline grows, hook button arrow nudges
  const tf = async (sel, pseudo) => await p.evaluate(({ sel, pseudo }) => getComputedStyle(document.querySelector(sel), pseudo || null).transform, { sel, pseudo })
  await p.locator('#tier ol > li').first().hover(); await p.waitForTimeout(350)
  ok((await tf('#tier ol > li')) !== 'none', `tier card transforms on hover (${await tf('#tier ol > li')})`)
  await p.locator('#klasemen ol li[data-rank="2"]').hover(); await p.waitForTimeout(350)
  ok((await tf('#klasemen ol li[data-rank="2"]')) !== 'none', 'klasemen row slides on hover')
  await p.locator('#benefit ul > li > div').first().hover(); await p.waitForTimeout(450)
  ok((await tf('#benefit ul > li > div')) !== 'none' && (await tf('#benefit ul > li > div .chip')) !== 'none', 'privilege block lifts + icon chip springs on hover')
  await p.locator('[data-rmc-card]').hover(); await p.waitForTimeout(500)
  const tilt = await tf('[data-rmc-card]')
  ok(/^matrix\(1, 0, 0, 1, 0, -6\)/.test(tilt), `RMC card straightens on hover (${tilt})`)
  ok((await tf('header nav a', '::after')).startsWith('matrix(0'), 'nav underline hidden at rest (scaleX 0)')
  await p.locator('header nav a').first().hover(); await p.waitForTimeout(350)
  ok(/^matrix\(1/.test(await tf('header nav a', '::after')), 'nav underline grows on hover (scaleX 1)')
  await p.locator('#hook a[href="#golden-sale"]').first().hover(); await p.waitForTimeout(350)
  ok((await tf('#hook a[href="#golden-sale"] svg')) !== 'none' && (await tf('#hook a[href="#golden-sale"]')) !== 'none', 'hook CTA lifts + arrow nudges on hover')
  await p.locator('#hook a[href="#/login"]').hover(); await p.waitForTimeout(350)
  ok(/^matrix\(1/.test(await tf('#hook a[href="#/login"]', '::after')), '"Cek poin-mu!" underline grows on hover')

  // R.015 — Lurd's styling rules: fonts, real photos, reveal on lists, press feedback, no em-dash
  const fam = await p.evaluate(() => ({ body: getComputedStyle(document.body).fontFamily, h1: getComputedStyle(document.querySelector('#hook h1')).fontFamily, code: getComputedStyle(document.querySelector('.t-code') || document.body).fontFamily, loaded: [...document.fonts].filter(f => f.status === 'loaded').map(f => f.family) }))
  ok(!/JetBrains/i.test(fam.body + fam.h1 + fam.code) && /Plus Jakarta Sans/.test(fam.body) && /Satoshi/.test(fam.code), `fonts: PJS body, Satoshi code, no JetBrains (${fam.code.slice(0, 40)})`)
  ok(fam.loaded.some(f => /Plus Jakarta Sans/.test(f)) && fam.loaded.some(f => /Satoshi/.test(f)), `webfonts loaded (${[...new Set(fam.loaded)].join(', ')})`)
  const srcs = await p.evaluate(() => [...document.querySelectorAll('#golden-sale img')].map(i => i.getAttribute('src')))
  ok(srcs.length >= 12 && srcs.every(x => /\.jpg$/.test(x)) && new Set(srcs).size === srcs.length, `Golden Sale uses ${srcs.length} distinct real photos`)
  ok((await p.locator('#golden-sale li[data-reveal]').count()) >= 12 && (await p.locator('#tier ol > li[data-reveal]').count()) === 6 && (await p.locator('#klasemen ol li[data-reveal]').count()) === 10, 'product / tier / klasemen items scroll-reveal (mobile motion)')
  ok(/transform/.test(await p.evaluate(() => getComputedStyle(document.querySelector('#hook a[href="#golden-sale"]')).transitionProperty)), 'buttons transition transform (press feedback)')
  ok(!/\u2014/.test(await p.evaluate(() => document.body.innerText)), 'no visible em-dash (U+2014)')
  // R.017 — brand palette, real logo, two-tier navbar, prize deck, doodle, tier motion, Satoshi figures, real contacts
  const heroBg = await p.evaluate(() => getComputedStyle(document.getElementById('hero')).backgroundColor)
  ok(heroBg === 'rgb(33, 26, 90)', `hero band is Resique navy (${heroBg})`)
  const logos = await p.evaluate(() => [...document.querySelectorAll('img[src*="resique-logo"]')].map(i => ({ where: i.closest('header') ? 'header' : i.closest('footer') ? 'footer' : 'other', w: i.naturalWidth, src: i.getAttribute('src') })))
  ok(logos.some(l => l.where === 'header' && l.w > 0 && /resique-logo\.png$/.test(l.src)) && logos.some(l => l.where === 'footer' && l.w > 0 && /resique-logo-white\.png$/.test(l.src)), `real Resique lockup in header (colour) + footer (white) → ${JSON.stringify(logos)}`)
  ok((await p.locator('header [data-utility] a[href^="tel:+6287815338811"]').count()) === 1 && (await p.locator('header [data-utility] a[href^="tel:"]').isVisible()), 'utility row: Customer Services tel link visible at 1440')
  ok(/08\.00 - 21\.00 WIB/.test(await text(p, 'header [data-utility]')) && /Jakarta, Indonesia/.test(await text(p, 'header [data-utility]')), 'utility row: jam buka + lokasi (mock content)')
  ok((await p.locator('header a[href="https://wa.me/6287815338811"]').count()) >= 1, 'Hubungi Kami → real WhatsApp CS number')
  const navTxt = await p.evaluate(() => [...document.querySelectorAll('header nav a')].map(a => a.textContent.trim()))
  ok(JSON.stringify(navTxt) === JSON.stringify(['Home', 'RMC', 'Golden Sale', 'Klasemen']), `nav = Home · RMC · Golden Sale · Klasemen (${navTxt.join(' · ')})`)
  const socials = await p.evaluate(() => [...document.querySelectorAll('a[href*="instagram.com/resiquesupermarket.id"], a[href*="youtube.com/@resiquesupermarketlaundry"], a[href*="facebook.com/p/Resique"]')].map(a => ({ t: a.target, r: a.rel })))
  ok(socials.length >= 6 && socials.every(x => x.t === '_blank' && /noopener/.test(x.r)), `real socials (IG/YT/FB) in header + footer, new tab + noopener (${socials.length})`)
  ok((await p.locator('footer a[href="https://www.resique.co.id/"]').count()) === 1 && (await p.locator('footer a[href^="mailto:operation.resique@gmail.com"]').count()) === 1 && (await p.locator('a[href*="wa.me/6281200000000"]').count()) === 0, 'footer: official site + email; placeholder WA number gone')
  await p.evaluate(() => window.scrollTo(0, 400)); await p.waitForTimeout(400)
  ok((await p.locator('header[data-scrolled]').count()) === 1 && (await tf('header[data-scrolled]')) !== 'none', 'header slides its utility row away on scroll (transform)')
  await p.locator('#benefit').scrollIntoViewIfNeeded(); await p.waitForTimeout(500)
  ok((await p.locator('header nav a[aria-current="page"]').count()) === 1 && /RMC/.test(await text(p, 'header nav a[aria-current="page"]')), 'scroll-spy marks RMC while the privilege section is in view')
  await p.evaluate(() => window.scrollTo(0, 0)); await p.waitForTimeout(300)
  ok((await p.locator('#hero .deck li').count()) === 4 && (await p.locator('#hero .deck[data-deal="in"]').count()) === 1, 'hero prize deck: 4 cards dealt in')
  await p.locator('#hero .deck').hover(); await p.waitForTimeout(600)
  ok((await tf('#hero .deck [data-front]')) !== 'none', 'deck front card straightens on hover')
  const doodle = await p.evaluate(() => { const s = document.querySelector('#hero svg[data-doodle]'); return s ? { op: parseFloat(getComputedStyle(s).opacity), sw: s.getAttribute('stroke-width') } : null })
  ok(doodle && doodle.op >= 0.15 && parseFloat(doodle.sw) >= 1.5, `hero doodle clearly visible (opacity ${doodle && doodle.op}, stroke ${doodle && doodle.sw})`)
  await p.locator('#tier ol > li').last().scrollIntoViewIfNeeded(); await p.waitForTimeout(900)
  const fig = await p.evaluate(() => { const el = document.querySelector('#tier ol > li .t-fig'); return { fam: getComputedStyle(el).fontFamily, w: getComputedStyle(el).fontWeight, black: [...document.fonts].some(f => f.family === 'Satoshi' && String(f.weight) === '900' && f.status === 'loaded') } })
  ok(/^Satoshi/.test(fig.fam) && fig.black, `tier figures set in Satoshi (${fig.fam.slice(0, 30)}, Satoshi 900 loaded=${fig.black})`)
  ok(await p.evaluate(() => [...document.querySelectorAll('#tier [data-pct]')].every(el => el.textContent === el.dataset.pct + '%')), 'tier % count-up settled at the real value')
  await p.locator('#tier ol > li').first().hover(); await p.waitForTimeout(400)
  const bar = await p.evaluate(() => getComputedStyle(document.querySelector('#tier ol > li .bar')).transform)
  ok(/^matrix\(1, 0, 0, 1/.test(bar) || /^matrix\(0\.9/.test(bar), `tier accent bar draws in on hover (${bar.slice(0, 18)})`)
  await p.locator('#benefit ul > li > div').first().hover(); await p.waitForTimeout(400)
  const tint = await p.evaluate(() => getComputedStyle(document.querySelector('#benefit ul > li > div'), '::before').opacity)
  ok(tint === '1', `privilege block tint fades in on hover (${tint})`)
  ok(errs.length === 0, `no page errors (${errs.length})`)
  await finish(b, errs, 'landing-verify')
})()
