/* Landing gate — 7 sections at 390 + 1440, marquee, tiers, klasemen, basket bar, no page errors. */
const { ok, launch, go, resetStores, text, minTapHeight, finish } = require('./_lib.cjs')

;(async () => {
  const { b, p, errs } = await launch({ width: 390, height: 844 })
  await resetStores(p)
  await go(p, '/')

  const ids = ['hook', 'hero', 'benefit', 'tier', 'cek-poin', 'golden-sale', 'klasemen']
  const order = await p.evaluate(ids => ids.map(id => { const el = document.getElementById(id); return el ? el.getBoundingClientRect().top + window.scrollY : -1 }), ids)
  ok(order.every(v => v >= 0), `7 sections present → ${JSON.stringify(order.map(Math.round))}`)
  ok(order.every((v, i) => i === 0 || v > order[i - 1]), 'sections in the specified order')

  const t = await text(p)
  ok(/Sekarang Turun Harga!/i.test(t) && /Banyak Bonusnya!/i.test(t) && /Resique Supermarket Laundry/i.test(await text(p, '#hook')), 'banner slide 1 = the mock\'s words: RESIQUE SUPERMARKET LAUNDRY / SEKARANG TURUN HARGA! / + BANYAK BONUSNYA!')
  ok(/Harga turun paling besar/.test(t), 'banner slide 3 names the biggest drops')
  ok((await p.locator('#benefit ul > li').count()) === 4, '4 benefits (the mock\'s set)')
  ok(/Diskon Belanja/.test(t) && /Langsung dipotong saat transaksi/.test(t) && /Gratis Ongkir/.test(t) && /Sesuai minimum pembelian/.test(t) && /Reward Point/.test(t) && /untuk ditukarkan voucher belanja/.test(t) && /Konsultasi Bisnis Laundry/.test(t) && /Bersama trainer Apique Academy untuk level Winner ke atas/.test(t), 'benefit titles + one-line explanations verbatim from the mock')
  ok((await p.locator('#benefit ul > li svg').count()) >= 4 && /Benefit Tak Terbatas dari Resique Member Card/.test(t) && (await p.locator('#benefit [data-member-card]').count()) === 1, 'benefit band: icons, mock title, member card')
  ok((await p.locator('#benefit [data-steps] ol > li').count()) === 4 && (await p.evaluate(() => [...document.querySelectorAll('#benefit [data-steps] .step-circle')].map(e => getComputedStyle(e).backgroundColor))).join('|') === 'rgb(113, 189, 65)|rgb(46, 42, 122)|rgb(46, 42, 122)|rgb(113, 189, 65)' && /Diskon\s*Belanja/.test(t) && /Dapatkan\s*Point/.test(t) && /Tukarkan\s*Voucher/.test(t) && /Nikmati\s*Keuntungannya/.test(t), 'four-step strip: Diskon Belanja → Dapatkan Point → Tukarkan Voucher → Nikmati Keuntungannya')
  ok(/Peringkat 1/.test(t) && (await p.locator('#klasemen ol li[data-rank="1"] svg').count()) === 1, 'klasemen leader card (rank 1 with trophy)')
  ok((await p.locator('#klasemen ol li[data-rank="2"] div[aria-hidden] > div').count()) === 1, 'klasemen rows carry spend bar')
  const ctaBg = await p.evaluate(() => getComputedStyle(document.getElementById('cek-poin')).backgroundColor)
  ok(ctaBg === 'rgb(33, 26, 90)', `CTA section is a navy block (${ctaBg})`)
  ok((await p.locator('#cek-poin ol li').count()) === 3, 'CTA section lists the 3 steps')
  ok(!/0–5%/.test(t) && (await p.evaluate(() => [...document.querySelectorAll('#tier ol > li')].pop().querySelector('[data-pct]').dataset.pct)) === '5', 'Ultimate column carries the 5% ceiling (no "0–5%" anywhere)')
  const card = await text(p, '[data-rmc-card]')
  ok(/Resique Member Card/.test(card) && /Poin RMC/.test(card) && /Laundry 24 Jam Kuningan/.test(card) && /Winner/.test(card), 'CTA band shows the demo member RMC card (tier + poin)')
  // title marks: every section h2 + the hook h1 carry the highlighter on the last word; it draws in (scaleX 1) once in view
  for (const sel of ['#hook h1', '#benefit h2', '#tier h2', '#cek-poin h2', '#golden-sale h2', '#klasemen h2']) {
    await p.locator(sel).scrollIntoViewIfNeeded(); await p.waitForTimeout(900)
    const m = await p.evaluate(sel => { const el = document.querySelector(sel + ' .mark'); return el ? getComputedStyle(el, '::before').transform : 'missing' }, sel)
    ok(/^matrix\(0\.99|^matrix\(1/.test(m), `${sel} highlighter mark drawn in (${m.slice(0, 22)})`)
  }
  await p.evaluate(() => window.scrollTo(0, 0)); await p.waitForTimeout(300)
  ok(/Tingkatkan Transaksi dan Dapatkan Hadiahnya!/.test(t) && /Belanja di Resique untuk dapatkan Hadiahnya, TANPA DIUNDI!/.test(t), 'prize section: mock title + sub verbatim')
  ok(/Cek poin-mu/.test(t) && /Daftar RMC Sekarang!/.test(t) && /Mulai nikmati seluruh keuntungan Member Resique mulai dari transaksi pertama/.test(t) && (await p.locator('#cek-poin [data-cta-benefits] li').count()) === 4, 'CTA band: mock title + sub + four benefit highlights; "Cek poin-mu!" link kept in the banner')
  ok((await p.locator('#hero [data-prize-card]').count()) === 4 && (await p.locator('#hero [data-prize-card] img').count()) === 4 && (await p.locator('#hero [data-prize-card] .t-fig').count()) === 4 && /Pt/.test(await text(p, '#hero')), 'prize grid: 4 prize cards with photo + point cost')
  ok((await p.locator('#tier h3:visible').count()) === 6, '6 tier cards visible (mobile ladder / desktop cards)')
  ok(/\*Mitra Apique Management memiliki diskon minimal 3% sejak Starter\. Jika diskon tier lebih besar, itu yang dipakai\./.test(t), 'Mitra floor note verbatim from the mock')
  // RSQ-RMC-001 v2.0 §3: ongkir ≥ Rp500 rb (Starter–Intermediate) / ≥ Rp350 rb (Winner+); konsultasi 1/1/2 sesi per bulan; no "tanpa minimum"
  const tierTxt = await p.evaluate(() => [...document.querySelectorAll('#tier ol > li')].map(li => li.innerText.replace(/\s+/g, ' ')))
  ok(tierTxt.length === 6 && tierTxt.slice(0, 3).every(x => /Gratis Ongkir Min Belanja Rp 500\.000/.test(x)) && tierTxt.slice(3).every(x => /Gratis Ongkir Min Belanja Rp 350\.000/.test(x)), 'tier columns: Gratis Ongkir / Min Belanja / Rp 500.000 ×3 then Rp 350.000 ×3 (mock wording, policy numbers)')
  ok(tierTxt.every(x => /Benefit Diskon Tiap Transaksi/.test(x) && /Gratis Sesi Konsultasi Bisnis/.test(x) && /Belanja 6 Bulan \(Rp\)/.test(x)) && /1x \/bulan/.test(tierTxt[3]) && /1x \/bulan/.test(tierTxt[4]) && /2x \/bulan/.test(tierTxt[5]) && !/\/bulan\b.*konsul/i.test(tierTxt[0]) && !/x \/bulan/.test(tierTxt[0]), 'tier columns: mock row labels; konsultasi 1x / 1x / 2x per bulan from Winner')
  ok(!/tanpa minimum|Tanpa min\./i.test(t) && !/mulai tier Champion/.test(t) && !/Konsultasi Binis/.test(t), 'no drifted claims; the mock\'s "Binis" typo is not reproduced')
  ok(/0 – ?8\.999\.999/.test(tierTxt[0]) && /9\.000\.000 – ?17\.999\.999/.test(tierTxt[1]) && /≥ 120\.000\.000/.test(tierTxt[5]), 'tier bands inclusive: 0–8.999.999, 9.000.000–17.999.999, ≥ 120.000.000')
  ok((await p.locator('#klasemen ol li').count()) === 10, 'klasemen shows 10 rows')

  // no horizontal scroll at 390
  const sw = await p.evaluate(() => ({ sw: document.documentElement.scrollWidth, cw: document.documentElement.clientWidth }))
  ok(sw.sw === sw.cw, `no horizontal scroll (scrollWidth ${sw.sw} = clientWidth ${sw.cw})`)

  // basket bar hidden when empty, shown after add
  ok((await p.locator('[data-basket-bar]').getAttribute('aria-hidden')) === 'true', 'basket bar hidden when cart empty')
  await p.locator('#golden-sale button[aria-label^="Tambah"]').first().click()
  await p.waitForTimeout(400)
  ok((await p.locator('[data-basket-bar]').getAttribute('aria-hidden')) === 'false', 'basket bar visible after add')
  ok(/1 item/.test(await text(p, '[data-basket-bar]')), 'basket bar shows 1 item')
  const tap = await minTapHeight(p, '#golden-sale button, [data-basket-bar] a, [data-basket-bar] button')
  ok(tap >= 44, `tap targets ≥ 44px (min ${tap})`)

  // desktop
  await p.setViewportSize({ width: 1440, height: 900 })
  await p.waitForTimeout(500)
  const heights = await p.evaluate(ids => ids.map(id => document.getElementById(id).getBoundingClientRect().height), ['hero', 'benefit', 'tier'])
  ok(new Set(heights.map(h => Math.round(h / 50))).size >= 2 && heights[0] >= 280, `desktop sections vary in height (no uniform deck) → ${heights.map(Math.round)}`)
  const heroCols = await p.evaluate(() => { const g = document.querySelector('#hero ul'); return g ? getComputedStyle(g).gridTemplateColumns.split(' ').length : 0 })
  ok(heroCols === 4, `prize grid is 4 across on desktop (${heroCols} tracks)`)

  // hover motion (desktop): tier card lifts, klasemen row slides, nav link underline grows, hook button arrow nudges
  const tf = async (sel, pseudo) => await p.evaluate(({ sel, pseudo }) => getComputedStyle(document.querySelector(sel), pseudo || null).transform, { sel, pseudo })
  await p.locator('#tier ol > li').first().hover(); await p.waitForTimeout(350)
  ok((await tf('#tier ol > li')) !== 'none', `tier card transforms on hover (${await tf('#tier ol > li')})`)
  await p.locator('#klasemen ol li[data-rank="2"]').hover(); await p.waitForTimeout(350)
  ok((await tf('#klasemen ol li[data-rank="2"]')) !== 'none', 'klasemen row slides on hover')
  await p.locator('#benefit ul > li > div').first().hover(); await p.waitForTimeout(450)
  ok((await tf('#benefit ul > li > div')) !== 'none' && (await tf('#benefit ul > li > div .chip')) !== 'none', 'privilege block lifts + icon chip springs on hover')
  await p.locator('[data-rmc-card]').hover(); await p.waitForTimeout(500)
  const tilt = await tf('[data-rmc-card]')
  const tm = /matrix\(([^)]+)\)/.exec(tilt); const tv = tm ? tm[1].split(',').map(Number) : []
  ok(tv.length === 6 && Math.abs(tv[0] - 1) < 0.01 && Math.abs(tv[1]) < 0.01 && Math.abs(tv[5] + 6) < 0.5, `RMC card straightens on hover (${tilt})`)
  ok((await tf('header nav a', '::after')).startsWith('matrix(0'), 'nav underline hidden at rest (scaleX 0)')
  await p.locator('header nav a').first().hover(); await p.waitForTimeout(350)
  ok(/^matrix\(1/.test(await tf('header nav a', '::after')), 'nav underline grows on hover (scaleX 1)')
  await p.locator('#hook [role="tab"]').nth(0).click(); await p.waitForTimeout(900)
  await p.locator('#hook a[href="#golden-sale"]').first().hover(); await p.waitForTimeout(350)
  ok((await tf('#hook a[href="#golden-sale"] svg')) !== 'none' && (await tf('#hook a[href="#golden-sale"]')) !== 'none', 'hook CTA lifts + arrow nudges on hover')
  await p.locator('#hook a[href="#/login"]').hover(); await p.waitForTimeout(350)
  ok(/^matrix\(1/.test(await tf('#hook a[href="#/login"]', '::after')), '"Cek poin-mu!" underline grows on hover')

  // R.015 — Lurd's styling rules: fonts, real photos, reveal on lists, press feedback, no em-dash
  const fam = await p.evaluate(() => ({ body: getComputedStyle(document.body).fontFamily, h1: getComputedStyle(document.querySelector('#hook h1')).fontFamily, code: getComputedStyle(document.querySelector('.t-code') || document.body).fontFamily, loaded: [...document.fonts].filter(f => f.status === 'loaded').map(f => f.family) }))
  ok(!/JetBrains|Satoshi|mono/i.test(fam.body + fam.h1 + fam.code) && /Plus Jakarta Sans/.test(fam.body) && /^"?Plus Jakarta Sans/.test(fam.code), `fonts: PJS everywhere, no JetBrains / Satoshi / mono (${fam.code.slice(0, 40)})`)
  ok(fam.loaded.some(f => /Plus Jakarta Sans/.test(f)) && !fam.loaded.some(f => /Satoshi|JetBrains/.test(f)), `webfonts loaded (${[...new Set(fam.loaded)].join(', ')})`)
  const srcs = await p.evaluate(() => [...document.querySelectorAll('#golden-sale img')].map(i => i.getAttribute('src')))
  ok(srcs.length >= 12 && srcs.every(x => /\.jpg$/.test(x)) && new Set(srcs).size === srcs.length, `Golden Sale uses ${srcs.length} distinct real photos`)
  ok((await p.locator('#golden-sale li[data-reveal]').count()) >= 12 && (await p.locator('#tier ol > li[data-reveal]').count()) === 6 && (await p.locator('#klasemen ol li[data-reveal]').count()) === 10, 'product / tier / klasemen items scroll-reveal (mobile motion)')
  ok(/transform/.test(await p.evaluate(() => getComputedStyle(document.querySelector('#hook a[href="#golden-sale"]')).transitionProperty)), 'buttons transition transform (press feedback)')
  ok(!/\u2014/.test(await p.evaluate(() => document.body.innerText)), 'no visible em-dash (U+2014)')
  // R.017 — brand palette, real logo, two-tier navbar, prize deck, doodle, tier motion, Satoshi figures, real contacts
  const heroBg = await p.evaluate(() => getComputedStyle(document.getElementById('hero')).backgroundColor)
  ok((await p.evaluate(() => document.querySelectorAll('#hero > .band, #hero > svg, #hero.tex').length)) === 0, 'prize section: plain white, no bands / rings / grain (Lurd, 11 Sep)')
  ok(heroBg === 'rgb(255, 255, 255)' && (await p.evaluate(() => getComputedStyle(document.querySelector('#hook [data-banner]')).backgroundColor)) === 'rgb(13, 10, 41)' && (await p.evaluate(() => getComputedStyle(document.querySelector('#benefit > div')).backgroundColor)) === 'rgb(33, 26, 90)', `mock rhythm: white prize section, navy banner card, navy benefit band (${heroBg})`)
  const logos = await p.evaluate(() => [...document.querySelectorAll('img[src*="resique-logo"]')].map(i => ({ where: i.closest('header') ? 'header' : i.closest('footer') ? 'footer' : 'other', w: i.naturalWidth, src: i.getAttribute('src') })))
  ok(logos.some(l => l.where === 'header' && l.w > 0 && /resique-logo\.png$/.test(l.src)) && logos.some(l => l.where === 'footer' && l.w > 0 && /resique-logo-white\.png$/.test(l.src)), `real Resique lockup in header (colour) + footer (white) → ${JSON.stringify(logos)}`)
  ok((await p.locator('header [data-utility] a[href^="tel:+6287815338811"]').count()) === 1 && (await p.locator('header [data-utility] a[href^="tel:"]').isVisible()), 'utility row: Customer Services tel link visible at 1440')
  ok(/08\.00 - 21\.00 WIB/.test(await text(p, 'header [data-utility]')) && !/Lokasi|Jakarta, Indonesia/.test(await text(p, 'header [data-utility]')) && !/Lokasi/.test(await text(p, 'footer')), 'utility row: jam buka only (Lokasi removed, R.018)')
  ok((await p.locator('header a[href="https://wa.me/6287815338811"]').count()) >= 1, 'Hubungi Kami → real WhatsApp CS number')
  const navTxt = await p.evaluate(() => [...document.querySelectorAll('header nav a')].map(a => a.textContent.trim()))
  ok(JSON.stringify(navTxt) === JSON.stringify(['Home', 'RMC', 'Golden Sale', 'Klasemen']), `nav = Home · RMC · Golden Sale · Klasemen (${navTxt.join(' · ')})`)
  const socials = await p.evaluate(() => [...document.querySelectorAll('a[href*="instagram.com/resiquesupermarket.id"], a[href*="youtube.com/@resiquesupermarketlaundry"], a[href*="facebook.com/p/Resique"]')].map(a => ({ t: a.target, r: a.rel })))
  ok(socials.length >= 6 && socials.every(x => x.t === '_blank' && /noopener/.test(x.r)), `real socials (IG/YT/FB) in header + footer, new tab + noopener (${socials.length})`)
  ok((await p.locator('footer a[href="https://www.resique.co.id/"]').count()) === 1 && (await p.locator('footer a[href^="mailto:operation.resique@gmail.com"]').count()) === 1 && (await p.locator('a[href*="wa.me/6281200000000"]').count()) === 0, 'footer: official site + email; placeholder WA number gone')
  await p.evaluate(() => window.scrollTo(0, 400)); await p.waitForTimeout(400)
  ok((await p.locator('header[data-scrolled]').count()) === 1 && (await tf('header[data-scrolled]')) !== 'none', 'header slides its utility row away on scroll (transform)')
  await p.locator('#benefit').scrollIntoViewIfNeeded(); await p.waitForTimeout(500)
  ok((await p.locator('header nav a[aria-current="page"]').count()) === 1 && /RMC/.test(await text(p, 'header nav a[aria-current="page"]')), 'scroll-spy marks RMC while the privilege section is in view')
  await p.evaluate(() => window.scrollTo(0, 0)); await p.waitForTimeout(300)
  const doodle = await p.evaluate(() => { const s = document.querySelector('#hook svg[data-doodle]'); return s ? { op: parseFloat(getComputedStyle(s).opacity), sw: s.getAttribute('stroke-width') } : null })
  ok(doodle && doodle.op >= 0.15 && parseFloat(doodle.sw) >= 1.5, `banner doodle clearly visible (opacity ${doodle && doodle.op}, stroke ${doodle && doodle.sw})`)
  await p.locator('#tier ol > li').last().scrollIntoViewIfNeeded(); await p.waitForTimeout(900)
  const fig = await p.evaluate(() => { const el = document.querySelector('#tier ol > li .t-fig'); const cs = getComputedStyle(el); return { fam: cs.fontFamily, w: cs.fontWeight, fvn: cs.fontVariantNumeric } })
  ok(/^"?Plus Jakarta Sans/.test(fig.fam) && Number(fig.w) >= 800 && !/tabular/.test(fig.fvn), `tier figures in PJS 800, proportional digits, no tabular-nums (${fig.fam.slice(0, 30)}, ${fig.w}, ${fig.fvn})`)
  ok(!/tabular/.test(await p.evaluate(() => getComputedStyle(document.querySelector('.t-code') || document.body).fontVariantNumeric)) && !/tabular/.test(await p.evaluate(() => getComputedStyle(document.querySelector('.t-num') || document.body).fontVariantNumeric)), 'no tabular figures anywhere (t-code / t-num proportional)')
  ok(await p.evaluate(() => [...document.querySelectorAll('#tier [data-pct]')].every(el => el.textContent === el.dataset.pct + '%')), 'tier % count-up settled at the real value')
  await p.locator('#tier ol > li').first().hover(); await p.waitForTimeout(400)
  const bar = await p.evaluate(() => getComputedStyle(document.querySelector('#tier ol > li .bar')).transform)
  ok(/^matrix\(1, 0, 0, 1/.test(bar) || /^matrix\(0\.9/.test(bar), `tier accent bar draws in on hover (${bar.slice(0, 18)})`)
  await p.locator('#benefit ul > li > div').first().hover(); await p.waitForTimeout(400)
  const tint = await p.evaluate(() => getComputedStyle(document.querySelector('#benefit ul > li > div'), '::before').opacity)
  ok(tint === '1', `privilege block tint fades in on hover (${tint})`)
  // R.026 — banner slider (the mock)
  ok((await p.locator('#hook h1 .hook-word').count()) >= 3 && !/01 Sep 2026|31 Okt 2026/.test(await text(p, '#hook')), 'banner headline words stagger in; no campaign chip')
  const sl = await p.evaluate(() => { const tr = document.querySelector('#hook .banner-track'); return { slides: tr.querySelectorAll('[data-slide]').length, dots: document.querySelectorAll('#hook [role="tab"]').length, snap: getComputedStyle(tr).scrollSnapType, ox: getComputedStyle(tr).overflowX, w: tr.clientWidth, sw: tr.scrollWidth, phone: (() => { const im = document.querySelector('#hook [data-slide="harga"] img[data-hero-art]'); return !!im && /hero-phone\.webp$/.test(im.getAttribute('src')) && im.naturalWidth > 0 && document.querySelectorAll('#hook [data-slide="harga"] img').length === 1 })() && !document.querySelector('#hook svg.sticker') && document.querySelectorAll('#hook svg.wire').length >= 3 && (() => { const im = document.querySelector('#hook [data-slide="harga"] img[data-hero-art]'); const card = document.querySelector('#hook [data-banner]').getBoundingClientRect(); const r = im.getBoundingClientRect(); const h1 = document.querySelector('#hook h1').getBoundingClientRect(); return r.height >= card.height * (innerWidth >= 1024 ? 0.78 : 0.25) && Math.abs(r.bottom - card.bottom) < 8 && (innerWidth < 1024 || (Math.abs(r.right - card.right) < 2 && h1.right <= r.left + r.width * 0.09 + 1)) })() } })
  ok(sl.slides === 3 && sl.dots === 3 && /x/.test(sl.snap) && sl.ox === 'auto' && sl.sw >= sl.w * 3 - 2 && sl.phone, `banner: 3 snap slides + 3 dots + the mock's hero picture, no seal, sized like the source (${JSON.stringify(sl)})`)
  await p.locator('#hook [role="tab"]').nth(2).click(); await p.waitForTimeout(900)
  ok((await p.evaluate(() => Math.round(document.querySelector('#hook .banner-track').scrollLeft / document.querySelector('#hook .banner-track').clientWidth))) === 2 && (await p.locator('#hook [role="tab"][aria-selected="true"]').count()) === 1, 'banner dot 3 scrolls the track to slide 3 (Golden Sale!!)')
  await p.locator('#hook [role="tab"]').nth(0).click(); await p.waitForTimeout(900)
  const heads = await p.evaluate(() => [...document.querySelectorAll('#tier ol > li')].map(h => getComputedStyle(h).backgroundColor))
  ok(heads.length === 6 && new Set(heads).size === 6, `tier columns are six distinct full-colour cards (${heads.length})`)
  ok((await p.locator('#tier ol > li:last-child svg.lucide-crown').count()) === 1 && !/Tier tertinggi/.test(await text(p, '#tier')), 'Ultimate carries the crown, no "Tier tertinggi" chip')
  ok((await p.evaluate(() => getComputedStyle(document.querySelector('#tier [data-mark="x"]')).backgroundColor)) === 'rgb(155, 44, 44)' && (await p.evaluate(() => getComputedStyle(document.querySelector('#tier [data-mark="check"]')).backgroundColor)) === 'rgb(113, 189, 65)' && (await p.locator('#tier [data-mitra-note]').count()) === 1, 'tier marks: red cross disc / green check disc like the mock; Mitra note in a highlight block')
  ok((await p.locator('#tier ol > li [data-row="ongkir"] svg.lucide-check').count()) === 6 && (await p.locator('#tier ol > li [data-row="konsul"] svg.lucide-x').count()) === 3 && (await p.locator('#tier ol > li [data-row="konsul"] svg.lucide-check').count()) === 3, 'tier rows: filled check on every ongkir row, cross on konsultasi for the first three (mock icons)')
  ok((await p.evaluate(() => getComputedStyle(document.getElementById('tier'), '::before').backgroundImage)).includes('radial-gradient') && (await p.locator('#hero svg circle').count()) >= 4, 'section backgrounds: dot field on tiers, ring motif on the prize section')
  // R.020 — CTA highlights, footer doodle, card numerals in PJS
  ok((await p.locator('#cek-poin a[href="#/register"]').count()) === 1 && /Daftar Sekarang/.test(await text(p, '#cek-poin a[href="#/register"]')) && (await p.evaluate(() => getComputedStyle(document.querySelector('#cek-poin a[href="#/register"]')).backgroundColor)) === 'rgb(113, 189, 65)', 'CTA band: "Daftar Sekarang" is the brand-green pill (mock primary)')
  ok((await p.evaluate(() => getComputedStyle(document.querySelector('#cek-poin a[href="#/login"]')).backgroundColor)) === 'rgb(255, 255, 255)', 'CTA band: "Masuk & cek poin" is the white button')
  ok((await p.locator('footer svg[data-doodle="footer"]').count()) === 1, 'footer carries the doodle')
  ok(/^"?Plus Jakarta Sans/.test(await p.evaluate(() => getComputedStyle(document.querySelector('#tier ol > li [data-pct]')).fontFamily)), 'tier % set in Plus Jakarta Sans')
  // R.021 — mobile tier slider, marks right, hero rail on desktop, basket bar spring, doodle mobile mask
  const rowOrder = await p.evaluate(() => { const row = document.querySelector('#tier ol > li [data-row="ongkir"] > div'); return row ? [...row.children].map(c => c.tagName + (c.querySelector('svg') ? ':icon' : ':text')).join(',') : '' })
  ok(rowOrder === 'SPAN:icon,DIV:text', `tier rows: mark disc before the label, as in the mock (${rowOrder})`)
  await p.setViewportSize({ width: 390, height: 844 }); await p.waitForTimeout(400)
  await p.locator('#tier').scrollIntoViewIfNeeded(); await p.waitForTimeout(1500)
  const rail = await p.evaluate(() => { const ol = document.querySelector('#tier ol'); const cs = getComputedStyle(ol); return { ox: cs.overflowX, snap: cs.scrollSnapType, sw: ol.scrollWidth, cw: ol.clientWidth, active: document.querySelectorAll('#tier ol > li[data-active="true"]').length, dots: document.querySelectorAll('#tier [role="tab"]').length } })
  ok(rail.ox === 'auto' && /x/.test(rail.snap) && rail.sw > rail.cw * 2 && rail.active === 1 && rail.dots === 6, `mobile tier rail: horizontal snap slider with one active card + 6 dots (${JSON.stringify(rail)})`)
  ok((await p.evaluate(() => getComputedStyle(document.querySelector('#cek-poin svg[data-doodle]')).webkitMaskImage || getComputedStyle(document.querySelector('#cek-poin svg[data-doodle]')).maskImage)).includes('34%') && (await p.evaluate(() => { const g = document.querySelector('#hero ul'); return getComputedStyle(g).gridTemplateColumns.split(' ').length })) === 2, 'mobile: doodle masked to the lower half, prize grid 2 across')
  await p.locator('#golden-sale button[aria-label^="Tambah"]').first().click(); await p.waitForTimeout(100)
  ok((await p.evaluate(() => getComputedStyle(document.querySelector('[data-basket-bar]')).animationName)) === 'bar-in', 'basket bar springs in (bar-in keyframes)')
  // R.022 — klasemen podium
  await p.locator('#klasemen').scrollIntoViewIfNeeded(); await p.waitForTimeout(1400)
  const pod = await p.evaluate(() => { const li = [...document.querySelectorAll('#klasemen ol > li')].slice(0, 3); return { orders: li.map(l => getComputedStyle(l).order), bg1: getComputedStyle(li[0]).backgroundColor, prize: !!document.querySelector('#klasemen ol li[data-rank="1"] img'), bar: getComputedStyle(document.querySelector('#klasemen ol li[data-rank="4"] .bar-fill')).transform } })
  ok((await p.evaluate(() => getComputedStyle(document.querySelector('#klasemen ol li[data-rank="1"]')).flexDirection)) === 'row' && (await p.evaluate(() => [...document.querySelectorAll('#klasemen ol > li')].slice(0, 3).every(l => l.getBoundingClientRect().width > 300))), 'mobile podium: stacked full-width cards, rank 1 as a horizontal row')
  ok((pod.orders.join(',') === '2,1,3' || pod.orders.join(',') === '0,0,0') && pod.bg1 === 'rgb(33, 26, 90)' && pod.prize && (pod.bar === 'none' || /^matrix\(1,/.test(pod.bar)), `klasemen podium: rank 1 centre in navy with the prize chip, bars filled (${JSON.stringify(pod)})`)
  // R.024 — podium: silver / bronze differentiated, medal pop, spend count-up settled
  const pod2 = await p.evaluate(() => { const li = [...document.querySelectorAll('#klasemen ol > li')].slice(0, 3); const t = document.body.innerText; return { bgs: li.map(l => getComputedStyle(l).backgroundColor), medals: /Perak/.test(t) && /Perunggu/.test(t) && /Emas/.test(t), icons: li.slice(1).every(l => l.querySelector('svg.lucide-medal')), medalTf: getComputedStyle(li[0].querySelector('.medal')).transform, spends: li.every(l => { const el = l.querySelector('[data-spend]'); return el && el.textContent.replace(/\D/g, '') === el.dataset.spend }) } })
  ok(new Set(pod2.bgs).size === 3 && pod2.medals && pod2.icons && (pod2.medalTf === 'none' || /^matrix\(1, 0, 0, 1, 0, 0\)/.test(pod2.medalTf)) && pod2.spends, `podium: 3 distinct card colours, Emas / Perak / Perunggu, medal icons on 2–3, medal popped, spend count-up settled (${JSON.stringify(pod2).slice(0, 160)})`)
  // R.027 — the step strip cycles an active step; benefit icons per the mock; prize chips count up
  await p.locator('#benefit [data-steps]').scrollIntoViewIfNeeded(); await p.waitForTimeout(2000)
  ok((await p.locator('#benefit [data-steps] li[data-active="true"]').count()) === 1 && (await p.locator('#benefit ul > li svg.lucide-badge-percent, #benefit ul > li svg.lucide-truck, #benefit ul > li svg.lucide-star, #benefit ul > li svg.lucide-headset').count()) === 4, 'steps cycle one active step; benefit icons = badge-percent / truck / star / headset')
  ok(await p.evaluate(() => [...document.querySelectorAll('#hero [data-prize-card] .t-fig')].length === 4), 'prize chips carry the counted point figure')
  // R.028 — QR to the web, bigger benefit highlights, worked banner ground, playful Golden Sale ground
  const r28 = await p.evaluate(() => { const qr = document.querySelector('#cek-poin [data-site-qr] img'); const chip = document.querySelector('#cek-poin [data-cta-benefits] .chip'); return { qr: qr ? qr.naturalWidth : 0, qrSrc: qr ? qr.getAttribute('src') : '', chipH: chip ? chip.getBoundingClientRect().height : 0, hookBands: document.querySelectorAll('#hook > .band').length, saleBg: getComputedStyle(document.getElementById('golden-sale')).backgroundColor, wm: !!document.querySelector('#golden-sale .sale-watermark'), tags: 0 } })
  ok(r28.qr > 0 && /qr-site\.svg$/.test(r28.qrSrc) && /rmc-web-beta\.vercel\.app/.test(await text(p, '#cek-poin [data-site-qr]')), `Daftar RMC band: QR to the web renders (${r28.qrSrc}, ${r28.qr}px)`)
  ok(r28.chipH >= 56 && r28.hookBands === 2 && r28.saleBg === 'rgb(13, 10, 41)' && r28.wm, `benefit discs ≥ 56px, banner ground worked, Golden Sale on the dark band with watermark (${JSON.stringify(r28)})`)
  // R.029 — banner depth layers + pointer parallax; member card after the mock (swoosh, chip, perspective)
  await p.setViewportSize({ width: 1440, height: 900 }); await p.waitForTimeout(400)
  await p.evaluate(() => window.scrollTo(0, 0)); await p.waitForTimeout(300)
  const bb = await p.locator('#hook [data-banner]').boundingBox()
  await p.mouse.move(bb.x + bb.width * 0.9, bb.y + bb.height * 0.85); await p.waitForTimeout(700)
  const depth = await p.evaluate(() => { const near = document.querySelector('#hook [data-depth="near"]'); const far = document.querySelector('#hook [data-depth="far"]'); const m = s => { const t = getComputedStyle(s).transform; const a = /matrix\(([^)]+)\)/.exec(t); return a ? Math.abs(parseFloat(a[1].split(',')[4])) : 0 }; return { layers: document.querySelectorAll('#hook [data-depth]').length, near: m(near), far: m(far), grid: !!document.querySelector('#hook [data-depth="far"] svg line') } })
  ok(depth.layers === 3 && depth.grid && depth.near > depth.far && depth.near >= 10, `banner: 3 depth layers, floor grid, near layer shifts more than far under the pointer (${JSON.stringify(depth)})`)
  await p.mouse.move(5, 5)
  const mc = await p.evaluate(() => { const c = document.querySelector('#benefit [data-member-card]'); const cs = getComputedStyle(c); return { swoosh: !!c.querySelector('svg.swoosh path'), blue: cs.backgroundColor, id: /RMC 2025 0321 0839/.test(c.textContent) && /Lebih Rutin/.test(c.textContent) && /Lebih Untung/.test(c.textContent), persp: /matrix3d/.test(cs.transform), glow: /255, 255, 255/.test(cs.boxShadow) } })
  ok(mc.swoosh && mc.blue === 'rgb(29, 79, 184)' && mc.id && mc.persp && mc.glow, `member card from the photo: royal blue, green crescent, member id + tagline, glow, rests turned (${JSON.stringify(mc)})`)
  await p.evaluate(() => document.querySelector('#benefit [data-member-card]').scrollIntoView({ block: 'center' })); await p.waitForTimeout(400)
  await p.locator('#benefit [data-member-card]').hover({ force: true }); await p.waitForTimeout(1600)
  const swirl = await p.evaluate(() => { const c = document.querySelector('#benefit [data-member-card]'); const cs = getComputedStyle(c); return { anim: cs.animationName, fill: cs.animationFillMode, tf: cs.transform } })
  ok(swirl.anim === 'card-swirl' && swirl.fill === 'forwards' && /matrix/.test(swirl.tf), `member card swirls then zooms on hover (${swirl.anim}, ${swirl.fill})`)
  await p.mouse.move(5, 5)
  // R.030 — Golden Sale after the latest Figma: dark band, gold ribbon marquee, FLASH SALE chip, countdown ticking, red badges, Hemat chips
  await p.locator('#golden-sale').scrollIntoViewIfNeeded(); await p.waitForTimeout(600)
  const gs1 = await p.evaluate(() => ({ sec: (document.querySelector('#golden-sale [data-cd="Detik"]') || {}).textContent, ribbon: document.querySelectorAll('#golden-sale .ribbon .marquee-track li').length, flash: /Flash Sale/i.test(document.querySelector('#golden-sale').innerText), gold: getComputedStyle(document.querySelector('#golden-sale h2 .mark')).color, red: getComputedStyle(document.querySelector('#golden-sale article .bg-danger')).backgroundColor, hemat: document.querySelectorAll('#golden-sale article').length > 0 && [...document.querySelectorAll('#golden-sale article')].every(a => /Hemat Rp/.test(a.innerText)), boxes: document.querySelectorAll('#golden-sale [data-countdown] [data-cd]').length }))
  await p.waitForTimeout(1200)
  const gs2 = await p.evaluate(() => (document.querySelector('#golden-sale [data-cd="Detik"]') || {}).textContent)
  ok(gs1.boxes === 4 && gs1.sec !== gs2 && gs1.ribbon >= 6 && gs1.flash && gs1.gold === 'rgb(212, 160, 78)' && gs1.red === 'rgb(155, 44, 44)' && gs1.hemat, `Golden Sale: countdown ticks (${gs1.sec}→${gs2}), ribbon marquee, FLASH SALE chip, gold SALE!!, red -N% badges, Hemat chips (${JSON.stringify(gs1).slice(0, 120)})`)
  ok(/Harga spesial khusus Member Resique, diskon hingga \d+% untuk semua produk/.test(await text(p, '#golden-sale')) && (await p.locator('#klasemen .sale-watermark').count()) === 0 && (await p.locator('#klasemen span.float-6.rounded-full').count()) === 0 && (await p.locator('#klasemen svg circle').count()) >= 4, 'sale sub from the Figma with the live cut; klasemen ground: rings, no watermark, no confetti dots')
  // R.031 — hook ground ≠ prize ground, 720° swirl, steps banner, Mitra note in the Futura stack, klasemen arena
  const r31 = await p.evaluate(() => { const css = [...document.styleSheets].flatMap(sh => { try { return [...sh.cssRules] } catch { return [] } }); const kf = css.find(r => r.name === 'card-swirl'); const last = kf ? [...kf.cssRules].pop().style.transform : ''; const note = document.querySelector('#tier [data-mitra-note] p'); return { hook: getComputedStyle(document.getElementById('hook')).backgroundColor, hero: getComputedStyle(document.getElementById('hero')).backgroundColor, swirl: last, banner: !!document.querySelector('#benefit [data-steps] .rounded-xl.bg-white'), kicker: !/Cara kerjanya/i.test(document.querySelector('#benefit [data-steps]').innerText) && /4 langkah/.test(document.querySelector('#benefit [data-steps]').innerText), noteFam: note ? getComputedStyle(note).fontFamily : '', kl: getComputedStyle(document.getElementById('klasemen')).backgroundColor, klSpark: document.querySelectorAll('#klasemen svg.lucide-sparkles').length, jost: [...document.fonts].some(f => /Poppins/.test(f.family)), noteW: note ? getComputedStyle(note).fontWeight : '' } })
  ok(r31.hook !== r31.hero && r31.hook === 'rgb(238, 240, 248)' && r31.hero === 'rgb(255, 255, 255)', `banner section ground (${r31.hook}) differs from the prize section (${r31.hero})`)
  ok(/rotateY\(710deg\)/.test(r31.swirl) && /scale\(1\.12\)/.test(r31.swirl) && (await p.evaluate(() => { const css = [...document.styleSheets].flatMap(sh => { try { return [...sh.cssRules] } catch { return [] } }); const kf = css.find(r => r.name === 'card-swirl'); return kf ? kf.cssRules.length : 0 })) === 2, `member card: one continuous 720° swirl + zoom (${r31.swirl})`)
  ok(r31.banner && r31.kicker, 'steps sit in a highlight banner, no "Cara kerjanya" kicker')
  ok(/^Poppins/.test(r31.noteFam) && r31.jost && r31.noteW === '400', `Mitra note in Poppins Regular (${r31.noteFam.slice(0, 30)}, ${r31.noteW})`)
  ok(r31.kl === 'rgb(251, 245, 232)' && r31.klSpark >= 1, `klasemen arena: gold ground + sparkles (${r31.kl}, ${r31.klSpark})`)
  await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight)); await p.waitForTimeout(600)
  const gap = await p.evaluate(() => { const k = document.getElementById('klasemen'); const note = [...k.querySelectorAll('p')].pop(); return Math.round(document.querySelector('footer').getBoundingClientRect().top - note.getBoundingClientRect().bottom) })
  ok(gap <= 70, `klasemen note → footer gap tight (${gap}px)`)
  // R.035 — hero doodle is closed shapes only: no <line>, no open path (every path ends with z or is a circle/rect/ellipse)
  const dd = await p.evaluate(() => { const s = document.querySelector('#hook svg[data-doodle]'); const open = [...s.querySelectorAll('path')].filter(el => !/z\s*$/i.test(el.getAttribute('d') || '')).length; return { lines: s.querySelectorAll('line').length, open, shapes: s.querySelectorAll('path,circle,rect,ellipse').length } })
  ok(dd.lines === 0 && dd.open === 0 && dd.shapes >= 10, `hero doodle: closed smooth shapes only (${JSON.stringify(dd)})`)
  ok(errs.length === 0, `no page errors (${errs.length})`)
  await finish(b, errs, 'landing-verify')
})()
